server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-auth
          uri: 'http://localhost:8081'
          predicates:
            - Path=/api/auth/**
        - id: msvc-usuarios
          uri: 'http://localhost:8082'
          predicates:
            - Path=/api/usuarios/**
        - id: msvc-membresias
          uri: 'http://localhost:8083'
          predicates:
            - Path=/api/membresias/**
            - Path=/api/incluidos/**
            - Path=/api/planes/**

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: "clave-super-secreta-para-mi-proyecto-que-debe-ser-larga"