server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-auth
          uri: 'http://localhost:8081'
          predicates:
            - Path=/api/auth/**

        - id: msvc-usuarios
          uri: 'http://localhost:8082'
          predicates:
            - Path=/api/usuarios/**,/api/roles/**

        - id: msvc-membresias
          uri: 'http://localhost:8083'
          predicates:
            - Path=/api/membresias/**,/api/incluidos/**,/api/planes/**

        - id: msvc-servicios
          uri: 'http://localhost:8084'
          predicates:
            - Path=/api/servicios/**

        - id: msvc-gestionperfil
          uri: 'http://localhost:8085'
          predicates:
            - Path=/api/perfil/**

        - id: msvc-clases
          uri: 'http://localhost:8086'
          predicates:
            - Path=/api/clases/**,/api/inscripciones/**

        - id: msvc-tickets
          uri: 'http://localhost:8087'
          predicates:
            - Path=/api/historial/**,/api/tickets/**

        - id: msvc-resenas
          uri: 'http://localhost:8088'
          predicates:
            - Path=/api/resenas/**

        - id: msvc-reservas
          uri: 'http://localhost:8089'
          predicates:
            - Path=/api/reservas/**

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: "clave-super-secreta-para-mi-proyecto-que-debe-ser-larga"