server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_fitlifespa
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: "clave-super-secreta-para-mi-proyecto-que-debe-ser-larga"
  expiration: 86400000